# Generated by Django 3.1.5 on 2021-02-01 17:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_post_body'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='body',
        ),
    ]
